version: "3"

services:
  web:
    image: webdevops/php-apache:alpine-php7
    ports:
      - "4500:80"
    volumes:
      - ./www:/app

    links:
      - db
    networks:
      - default

  db:
    image: mysql
    command:
      [
        '--default-authentication-plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_general_ci'
      ]

    networks:
      - default

    environment:
      MYSQL_DATABASE: db_zucchetti
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - "8080:80"
    environment:
      MYSQL_ROOT_PASSWORD: root

volumes:
  persistent:
